version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: buying-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # MySQL 이미지가 요구하는 키들을 .env의 DB_* 값으로 매핑
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: